use_frameworks!

platform :ios, '11.0'

target 'ConfigurationProvider_Example' do
    pod 'ConfigurationProvider', :path => '../'

    target 'ConfigurationProvider_Tests' do
        inherit! :search_paths
    end

end
