use_frameworks!

platform :ios, '9.3'

target 'ConfigurationProvider_Example' do
    pod 'ConfigurationProvider', :path => '../Sources/'

    target 'ConfigurationProvider_Tests' do
        inherit! :search_paths
    end

end
