Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
source "https://rubygems.org"

gem "xcpretty"
gem "slather"
gem "cocoapods", "1.10.0"
gem "fastlane", "2.185.0"
gem "xcode-install"
gem "jazzy"