import_from_git(url: 'https://github.com/jjfernandes87/Lanes.git', path: 'fastlane/Fastfile-Public-Pod')
default_platform(:ios)

def changelogFile 
 "../CHANGELOG.md"
end

def pod_name
  "ConfigurationProvider"
end

def proj 
{
    plist: "./Example/#{pod_name}/Info.plist",
    xcodeproj: "./Example/#{pod_name}.xcodeproj/",
    workspace: "./Example/#{pod_name}.xcworkspace",
    repo_url: "https://github.com/jjfernandes87/ConfigurationProvider.git",
    scheme: "#{pod_name}-Example"
}
end

def cocoapods 
{
    podspec: "./Sources/#{pod_name}.podspec",
    pod_name: "#{pod_name}"
}
end
